pekko {
  loglevel = INFO

  remote.artery {
    transport = tcp
    canonical.hostname = ${clustering.ip}
    canonical.port = ${clustering.port}
  }

  cluster {
    seed-nodes = [
      "pekko://"${clustering.cluster.name}"@"${clustering.seed-ip}":"${clustering.seed-port}
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

  actor {
    provider = cluster
    serialization-bindings {
      "it.unibo.SmartHomeAlarmSystemProtocol$CborSerializable" = jackson-cbor
    }
  }
}

clustering {
  ip = "127.0.0.1"
  ip = ${?CLUSTER_IP}

  port = 1600
  port = ${?CLUSTER_PORT}

  seed-ip = "127.0.0.1"
  seed-ip = ${?PEKKO_SEED_HOST}

  seed-port = 1600
  seed-port = ${?PEKKO_SEED_PORT}

  cluster.name = "DistributedSmartHomeAlarmSystem"
}