pekko {
  loglevel = INFO

  remote.artery {
    transport = tcp
    canonical.hostname = ${node.host}
    canonical.port = ${node.port}
  }

  cluster {
    seed-nodes = [
      "pekko://"${cluster.name}"@"${cluster.seed-host}":"${cluster.seed-port}
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

  actor {
    provider = cluster
    serialization-bindings {
      "it.unibo.SmartHomeAlarmSystemProtocol$CborSerializable" = jackson-cbor
    }
  }
}

node {
  host = "127.0.0.1"
  host = ${?NODE_HOST}

  port = 1600
  port = ${?NODE_PORT}
}

cluster {
  name = "DistributedSmartHomeAlarmSystem"

  seed-host = "127.0.0.1"
  seed-host = ${?SEED_HOST}

  seed-port = 1600
  seed-port = ${?SEED_PORT}
}